server:
  port: 8080

spring:
  application:
    name: roomreservationservices
  mvc:
    format:
      date: yyyy-MM-dd

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

